#!/usr/bin/php
<?php

    // Recreate the abs path if required
    if (!defined('ABSPATH')) {
        define('ABSPATH', __DIR__);
    }

    // Composer library
    require_once __DIR__ . '/vendor/autoload.php'; 

    // Initiate Cli package
    $Package = new \App\Blueprint\Utilities\Cli();

    // Capture the primary command and method from the terminal
    $command  = $argv[1] ?? null; // e.g., 'localstorage'
    $method   = $argv[2] ?? null; // e.g., 'setvalue'

    // Slice all remaining elements starting from index 3 onward to accept unlimited values
    $extraArguments = array_slice($argv, 3);

    // Pass the command, method, and unpack all dynamic arguments into the Cli class
    $Package->command($command, $method, ...$extraArguments);