<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $name ?> | Test email</title>
    <style>
        body { margin: 0; padding: 0; font-family: 'Segoe UI', Arial, sans-serif; background-color: #f8f9fa; }
        .wrapper { width: 100%; table-layout: fixed; background-color: #f8f9fa; padding: 20px 0; }
        .main { background-color: #ffffff; margin: 0 auto; width: 100%; max-width: 600px; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden; }
        .header { background-color: #2c3e50; color: #ffffff; padding: 30px; text-align: center; }
        .content { padding: 40px 30px; color: #444444; line-height: 1.6; }
        .badge { background: #e1f5fe; color: #0288d1; padding: 4px 10px; border-radius: 4px; font-weight: bold; font-size: 12px; }
        .data-table { width: 100%; margin: 20px 0; border-collapse: collapse; }
        .data-table td { padding: 10px; border-bottom: 1px solid #f0f0f0; font-size: 14px; }
        .label { font-weight: bold; color: #7f8c8d; width: 30%; }
        .footer { padding: 20px; background-color: #f1f1f1; text-align: center; font-size: 12px; color: #95a5a6; }
        code { background: #f4f4f4; padding: 2px 4px; border-radius: 3px; font-family: monospace; }
    </style>
</head>
<body>
    <center class="wrapper">
        <table class="main" role="presentation">
            <tr>
                <td class="header">
                    <h1 style="margin: 0; font-size: 24px;"><?= $name ?></h1>
                    <p style="margin: 5px 0 0; opacity: 0.8;">Standard test email</p>
                </td>
            </tr>

            <tr>
                <td class="content">
                    <h2 style="margin-top: 0; color: #2c3e50;">Server details</h2>
                    <p><?= $description ?></p>
                    
                    <table class="data-table">
                        <tr>
                            <td class="label">Version:</td>
                            <td><span class="badge"><?= $version ?></span></td>
                        </tr>
                        <tr>
                            <td class="label">Branch:</td>
                            <td><code><?= $branch ?></code></td>
                        </tr>
                    </table>

                    <p style="margin-bottom: 0;">This is an automated test generated by the <strong>SimplyWeb</strong> email engine.</p>
                </td>
            </tr>

            <tr>
                <td class="footer">
                    <p style="margin: 0;">Sent by <?= $name ?></p>
                </td>
            </tr>
        </table>
    </center>
</body>
</html>